'use client';
// Standalone local-verification page for the capability/flow map.
// Loads ``/public/_demo/{graph,flows}.json`` and renders the real
// ``MapCanvas`` with them — no backend, no Postgres, no Redis.
// Generated by ``scripts/demo_flow_blob.py --rich``.

import { useEffect, useState } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import {
  MapCanvas,
  ROOT_FOCUS,
  type FocusPath,
} from '@/components/code-graph/map-canvas';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import type { FlowJsonBlob, RepoGraphBlob } from '@/types/api';

function encode(focus: FocusPath): string | null {
  if (!focus.capabilityId) return null;
  const out = [focus.capabilityId];
  if (focus.flowId) {
    out.push(focus.flowId);
    if (focus.stepNodeId) out.push(encodeURIComponent(focus.stepNodeId));
  }
  return out.join('/');
}

function parse(raw: string | null): FocusPath {
  if (!raw) return ROOT_FOCUS;
  const [c, f, s] = raw.split('/', 3);
  return {
    capabilityId: c || null,
    flowId: f || null,
    stepNodeId: s ? decodeURIComponent(s) : null,
  };
}

export default function MapDemoPage() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const [flows, setFlows] = useState<FlowJsonBlob | null>(null);
  const [graph, setGraph] = useState<RepoGraphBlob | null>(null);

  useEffect(() => {
    Promise.all([
      fetch('/_demo/flows.json').then((r) => r.json()),
      fetch('/_demo/graph.json').then((r) => r.json()),
    ]).then(([f, g]) => {
      setFlows(f);
      setGraph(g);
    });
  }, []);

  const focus = parse(searchParams.get('p'));
  const setFocus = (next: FocusPath) => {
    const params = new URLSearchParams(searchParams.toString());
    const enc = encode(next);
    if (enc) params.set('p', enc);
    else params.delete('p');
    router.replace(`?${params.toString()}`, { scroll: false });
  };

  return (
    <div className="flex h-screen flex-col p-6">
      <header className="mb-4">
        <h1 className="text-xl font-semibold">Capability / Flow Map demo</h1>
        <p className="text-xs text-muted-foreground">
          Loaded statically from <code>/public/_demo/</code>. Click a tile,
          press Esc or ArrowUp to drill out, Home for LOD 0.
        </p>
      </header>
      {flows ? (
        <Tabs defaultValue="map" className="flex min-h-0 flex-1 flex-col">
          <TabsList className="self-start">
            <TabsTrigger value="map">Map</TabsTrigger>
          </TabsList>
          <TabsContent value="map" className="min-h-0 flex-1 overflow-hidden">
            <MapCanvas
              blob={flows}
              focus={focus}
              onFocusChange={setFocus}
              repoId={0}
              graphBlob={graph}
            />
          </TabsContent>
        </Tabs>
      ) : (
        <p className="text-sm text-muted-foreground">Loading demo blob…</p>
      )}
    </div>
  );
}
