"""Harness engineering — onboard repos with structure, linting, and entropy management."""

from __future__ import annotations

from agent import sh
from agent.workspace import _run_git, clone_repo, create_branch, push_branch
from shared.logging import setup_logging

log = setup_logging("harness")


HARNESS_ONBOARDING_PROMPT = """\
You are onboarding this repository for an autonomous AI coding agent (auto-agent).
Your job is to add "harness engineering" infrastructure that keeps AI-generated code
high quality, well-structured, and maintainable.

## What to do

Analyze this repo's tech stack, structure, and patterns, then add the following
infrastructure. Adapt everything to this specific repo — do NOT use generic templates.

### 1. CLAUDE.md (create or update)

Create a `CLAUDE.md` in the repo root with:
- **Build/test/lint commands**: exact commands to build, test, and lint this project
- **Architectural constraints**: define the dependency layers for THIS repo
- **Module boundaries**: which directories own which concerns, what should NOT import what
- **Code style rules**: patterns specific to this repo
- **File organization rules**: where new files should go, max file size guidelines

### 2. Linting & Static Analysis

Based on the tech stack, add or enhance linting configuration:
- **Python**: ruff.toml or pyproject.toml [tool.ruff]
- **JavaScript/TypeScript**: eslint config with strict rules
- **Go**: golangci-lint config
- **Other**: idiomatic linter for the ecosystem

### 3. Pre-commit hooks

Add or update `.pre-commit-config.yaml` with hooks for linting, whitespace, large files.

### 4. Architecture Decision Records (ADR)

Create `docs/decisions/` with a template and the onboarding ADR.

### 5. Entropy management config

Create `.auto-agent/entropy.yml` with scanning rules for dead code, stale docs, naming drift.

## Rules

- Do NOT change any existing application code or tests.
- Do NOT break existing CI/CD or workflows.
- If CLAUDE.md already exists, preserve existing content and add constraints section.
- Keep all additions minimal and idiomatic for the tech stack.
- Commit with message: "Add harness engineering infrastructure for auto-agent"
"""


async def handle_harness_onboarding(repo_id: int, repo_name: str) -> str | None:
    """Run harness onboarding for a repo using the agent. Returns PR URL or None."""
    from agent.lifecycle.factory import create_agent

    log.info(f"Starting harness onboarding for repo '{repo_name}'")

    # Read the repo in-process from the DB. The old GET /repos loopback is
    # org-scoped (current_org_id_dep) and the agent process has no token, so it
    # 401'd and model_validate choked on the {"detail": ...} error body.
    from agent.lifecycle._orchestrator_api import get_repo, mark_repo_harness_onboarded

    repo_data = await get_repo(repo_name)
    if not repo_data:
        log.error(f"Repo '{repo_name}' (id={repo_id}) not found")
        return None

    owner_and_name = repo_data.url.replace("https://github.com/", "").replace(".git", "").replace("/", "-")
    ws_name = f"harness-{owner_and_name}"
    workspace = await clone_repo(repo_data.url, task_id=0, default_branch=repo_data.default_branch, workspace_name=ws_name, repo_id=None)  # onboarding: no repo_id

    branch_name = "auto-agent/harness-onboarding"

    try:
        await _run_git("branch", "-D", branch_name, cwd=workspace)
        await _run_git("push", "origin", "--delete", branch_name, cwd=workspace)
        await create_branch(workspace, branch_name)

        # Run the agent with full tools (needs to write files)
        agent = create_agent(workspace, readonly=False, max_turns=30)
        result = await agent.run(HARNESS_ONBOARDING_PROMPT)
        log.info(f"Harness onboarding output for '{repo_name}': {result.output[:500]}...")

        await push_branch(workspace, branch_name)

        pr_body = (
            "## Harness Engineering Onboarding\n\n"
            "This PR adds infrastructure to keep AI-generated code high quality:\n\n"
            "- **CLAUDE.md** — Architectural constraints and conventions\n"
            "- **Linting config** — Strict rules enforced mechanically\n"
            "- **Pre-commit hooks** — Catch violations before they land\n"
            "- **ADR system** — `docs/decisions/` for design decisions\n"
            "- **Entropy config** — `.auto-agent/entropy.yml` for scanning\n\n"
            "---\n*Generated by auto-agent harness engineering*"
        )

        from shared.github_auth import get_github_token

        gh_token = await get_github_token()
        result = await sh.run(
            [
                "gh", "pr", "create",
                "--title", f"[auto-agent] Harness engineering onboarding for {repo_name.split('/')[-1]}",
                "--body", pr_body,
                "--base", repo_data.default_branch,
                "--head", branch_name,
            ],
            cwd=workspace,
            timeout=30,
            env={"GH_TOKEN": gh_token},
        )
        pr_url = result.stdout.strip()

        if result.failed:
            log.error(f"PR creation failed for harness onboarding: {result.stderr.strip() or pr_url}")
            return None

        if not pr_url.startswith("http"):
            log.error(f"Invalid PR URL from gh: {pr_url!r}")
            return None

        log.info(f"Harness onboarding PR created for '{repo_name}': {pr_url}")

        await mark_repo_harness_onboarded(repo_id, pr_url)

        return pr_url

    except Exception:
        log.exception(f"Harness onboarding failed for '{repo_name}'")
        return None
